---
name: Lint code with ruff

on:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run ruff
        id: format
        uses: seravo/actions/pyruff@v1.17.1
        with:
          dev_requirements_path: dev-requirements.txt
